# Generated by Django 5.1.14 on 2026-02-04 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/")),
                ("description", models.TextField()),
                (
                    "skin_type_suitability",
                    models.CharField(help_text="e.g. Oily, Dry, All", max_length=100),
                ),
                ("benefits", models.TextField(help_text="Key benefits of the product")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredients",
                    models.ManyToManyField(blank=True, to="app.ingredient"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "morning_products",
                    models.ManyToManyField(
                        blank=True, related_name="morning_routines", to="app.product"
                    ),
                ),
                (
                    "night_products",
                    models.ManyToManyField(
                        blank=True, related_name="night_routines", to="app.product"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkinScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="scans/")),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("acne_score", models.IntegerField(default=0)),
                ("oiliness_score", models.IntegerField(default=0)),
                ("wrinkle_score", models.IntegerField(default=0)),
                ("hydration_score", models.IntegerField(default=0)),
                ("overall_analysis", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
