# Generated by Django 5.1.14 on 2026-02-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="view_username",
            field=models.CharField(
                blank=True, help_text="Username for testing", max_length=150
            ),
        ),
    ]
