# Generated by Django 5.1.14 on 2026-02-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userprofile_view_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Normal", "Normal"),
                    ("Dry", "Dry"),
                    ("Oily", "Oily"),
                    ("Combination", "Combination"),
                    ("Sensitive", "Sensitive"),
                ],
                default="Normal",
                max_length=20,
            ),
        ),
    ]
