# Generated by Django 5.1.14 on 2026-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_userprofile_age_userprofile_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="benefits",
            field=models.TextField(
                blank=True, help_text="Primary benefits (e.g. Anti-aging)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="side_effects",
            field=models.TextField(
                blank=True, help_text="Potential risks (e.g. Sun sensitivity)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="suitable_skin_types",
            field=models.CharField(
                blank=True, help_text="e.g. Oily, Mature", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unsuitable_skin_types",
            field=models.CharField(
                blank=True, help_text="e.g. Sensitive, Rosacea", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="SkinProblem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "avoid_ingredients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="aggravates_problems",
                        to="app.ingredient",
                    ),
                ),
                (
                    "recommended_ingredients",
                    models.ManyToManyField(
                        blank=True, related_name="treats_problems", to="app.ingredient"
                    ),
                ),
            ],
        ),
    ]
