# Generated by Django 5.1.14 on 2026-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_ingredient_benefits_ingredient_side_effects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="benefits",
            field=models.TextField(
                blank=True, default="", help_text="Primary benefits (e.g. Anti-aging)"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="side_effects",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Potential risks (e.g. Sun sensitivity)",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="suitable_skin_types",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Oily, Mature", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unsuitable_skin_types",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Sensitive, Rosacea",
                max_length=200,
            ),
        ),
    ]
