# Generated by Django 5.1.14 on 2026-02-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_cart_cartitem_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="skinscan",
            name="dark_circles_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skinscan",
            name="health_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skinscan",
            name="skin_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
