# Generated by Django 5.2.11 on 2026-03-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_skinscan_dark_circles_score_skinscan_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
